### ISSUE TITLE
Cannot find module './../../core/queue/queuemanager'

### ISSUE THREAD

**Issue by debben** [arafato/azurite#110]
It looks like there's a case mismatch between the references and the actual filename for QueueManager.js. All of the require statements use 'queuemanager' but the filename is QueueManager.js. I get the following both when I run 'npm run queue' and when I run 'docker run arafato/azurite:1.1.0' I get the following:
`
 **PANIC** Something unexpected happened! Queue Storage Emulator may be in an inconsistent state!
{ Error: Cannot find module './../../core/queue/queuemanager'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/don/src/azurite/lib/middleware/queue/validation.js:6:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at env.init.then (/home/don/src/azurite/lib/AzuriteQueue.js:36:25)
    at tryCatcher (/home/don/src/azurite/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/don/src/azurite/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/don/src/azurite/node_modules/bluebird/js/release/promise.js:569:18) code: 'MODULE_NOT_FOUND' }
`

**Comment by arafato** [comment]
Thanks for reporting @debben ! Just published a fix under version 1.3.0
