### ISSUE TITLE
PutBlockList fails

### ISSUE THREAD

**Issue by AdallomRoy** [arafato/azurite#28]
Got this exception:

``
**PANIC** Something unexpected happened! Emulator may be in an inconsistent state!
ReferenceError: AError is not defined
    at xml2jsAsync.then.catch (/usr/lib/node_modules/azurite/lib/api/PutBlockList.js:51:27)
    at tryCatcher (/usr/lib/node_modules/azurite/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/azurite/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/lib/node_modules/azurite/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/azurite/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/lib/node_modules/azurite/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/usr/lib/node_modules/azurite/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node_modules/azurite/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/azurite/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
PUT /devstoreaccount1/testContainer/a/data0?comp=blocklist 500 19.672 ms - 21
``

**Comment by arafato** [comment]
Hi @AdallomRoy , fixed the `ReferenceError` (Azurite 0.6.4). Azurite should now return an `HTTP 400` since the XML seems to be invalid. Can you paste the XML in here to check? Thanks!

**Comment by AdallomRoy** [comment]
Hi @arafato,

The XML looks fine, I captured it with tcpdump:
``
<?xml version="1.0" encoding="utf-8"?><BlockList><Latest>ICAgICAgICAgMA==</Latest></BlockList>
``

**Comment by AdallomRoy** [comment]
I think there's a general issue there with how the body is being parsed (or received). I tried to print it using console.log and it doesn't seem to be the XML I sent...

**Comment by AdallomRoy** [comment]
Additional info - I found out that the body is not being parsed at all by the raw parser, since the Azure go sdk doesn't send any content-type, which causes the type-is library to return no-match for the content.
